export const env = {
  DATABASE_URL: process.env.IS_TEST
    ? process.env.DATABASE_URL_TEST!
    : process.env.DATABASE_URL!,
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID!,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET!,
  HOST_NAME: process.env.HOST_NAME!,
  NODE_ENV: process.env.NODE_ENV!,
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY!,
  STRIPE_PRICE_ID: process.env.STRIPE_PRICE_ID!,
  STRIPE_WEBHOOK_SECRET: process.env.STRIPE_WEBHOOK_SECRET!,
  STRIPE_DISCOUNT_COUPON_ID: process.env.STRIPE_DISCOUNT_COUPON_ID,
  RECAPTCHA_SECRET_KEY: process.env.RECAPTCHA_SECRET_KEY!,
  MAILING_LIST_ENDPOINT: process.env.MAILING_LIST_ENDPOINT!,
  MAILING_LIST_PASSWORD: process.env.MAILING_LIST_PASSWORD!,
  RESEND_API_KEY: process.env.RESEND_API_KEY!,
  FROM_EMAIL_ADDRESS: process.env.FROM_EMAIL_ADDRESS!,
};
